[package]
name = "tribute-passes"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Compiler passes for Tribute (CST to TrunkIR lowering, type inference, etc.)"

[dependencies]
salsa.workspace = true
tree-sitter.workspace = true
tree-sitter-tribute.workspace = true
tribute-core.workspace = true
tribute-trunk-ir.workspace = true
