id = "tribute-lang"
name = "Tribute Language"
version = "0.1.0"
schema_version = 1
description = "Tribute language support for Zed"
repository = "https://github.com/Kroisse/tribute"
authors = ["Eunchong Yu <kroisse@gmail.com>"]

[grammars.tribute]
repository = "https://github.com/Kroisse/tree-sitter-tribute"
rev = "0.1.0"
